ShoppingCart/Models/Cart.cs
namespace ShoppingCart.Models
{
    public class Cart
    {
        public int ProductId { get; set; }

        public string ProductName { get; set; }

        public int Quantity { get; set; }

        public double Price { get; set; }

        public double Total
                {
                    get { return Quantity * Price; }
                }

        public string Image { get; set; }

        public Cart(Products product)
                {
           
                    ProductId = product.ProductId;
                    ProductName = product.Pname;
                    Price = product.Price;
                    Quantity = 1;
                    Image = product.Pimage;
        }


    }
}

ShoppingCart/Models/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ShoppingCart.Models
{
    public class CategoriesViewComponent:ViewComponent
    {
        public Context _context;
       public CategoriesViewComponent(Context c)
        {
            _context = c;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _context.categories.ToListAsync());
        }
    }
}

ShoppingCart/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Models;
using System.Diagnostics;
using System.Runtime.Intrinsics.Arm;

namespace ShoppingCart.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public readonly Context _context;

        public HomeController(ILogger<HomeController> logger,Context context)
        {
            _logger = logger;
            _context = context;
        }

    

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Shop(string CategorySlug = "")
        {
            
            var count = _context.products.Select(x=>x.Brand).Count();
            HttpContext.Session.SetInt32("countbrands",count);
            if (CategorySlug == "")
            {
                return View(_context.products.OrderByDescending(x => x.ProductId).ToList());
            }
            else
            {
                var category = _context.categories.Where(a=>a.slug== CategorySlug).FirstOrDefault();
                if (category != null)
                {
                    var probycat = _context.products.Where(p=>p.CategoryId==category.CategoryId) ;
                    return View(probycat.OrderByDescending(v => v.ProductId).ToList());
                }
                else { return RedirectToAction("Shop"); }
            }
        }

        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Cart()
        {
            return View();
        }

        public IActionResult ShopSingle(int? Id) {
            var x = _context.products.Find(Id);
            return View(x);
        }

        public IActionResult Profile(LoginRegister d)
        {

            var x = _context.loginRegister.Where(a => a.Email == HttpContext.Session.GetString("i"));
            return View(x.ToList());
        }

        public IActionResult CheckOut()
        {

            return View();
        }
    }
}

ShoppingCart/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using ShoppingCart.Models;

namespace ShoppingCart.Controllers
{
    public class LoginController : Controller
    {
        public Context _context;

        public LoginController(Context c)
        {
            _context = c;
            
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(LoginRegister a)
        {
            var x = _context.loginRegister.FirstOrDefault(i=>i.Email==a.Email);
            if (a.Email.Equals(x?.Email))
            {

				ViewBag.c = "Already Have an Account using this Email";
				return View();
                
			}
            else
            {
				if (a.Password == a.PasswordConfirmed)
				{

					_context.loginRegister.Add(a);
					_context.SaveChanges();
					return RedirectToAction(nameof(UserLogin));

				}
				else
				{
					ViewBag.c = "Password is not confirmed";
					return View();
				}

			}
            return RedirectToAction("UserLogin");

        }

        [HttpGet]
        public IActionResult UserLogin() {
            return View();
        }

         [HttpPost]
        public IActionResult UserLogin(LoginRegister a) {

            if(a.Email== "admin@gmail.com" && a.Password== "1234567")
            {
                HttpContext.Session.SetString("adm", a.Email);
                return RedirectToAction("Dashboard" , "Products");
            }

           var x = from i in _context.loginRegister
                    where i.Email.Equals(a.Email)
                    && i.Password.Equals(a.Password)
                    select i; 
            if (x.Any())
            {
                HttpContext.Session.SetString("i", a.Email);
                return RedirectToAction("Index", "Home");
            }

            else
            {
                ViewBag.m = "Invalid Credentials";
                return View();
            }

            //var c = _context.loginRegister.Where(b => b.Email == a.Email && b.Password == a.Password);
            //if (c.Any())
            //{
            //    return RedirectToAction("Index", "Home");
            //}
            //else
            //{
            //    ViewBag.m = "Invalid Credentials";
            //    return View();
            //}
     
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var x = _context.loginRegister.Find(id);
            return View(x);
        }

        [HttpPost]
        public IActionResult Edit(LoginRegister a)
        {
            _context.Update(a);
            _context.SaveChanges();
            return RedirectToAction("Profile","Home");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index","Home");
        }
    }
} 

ShoppingCart/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="site-wrap">



    <div class="bg-light py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0"><a asp-controller="Home" asp-action="Index">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">About</strong></div>
            </div>
        </div>
    </div>

    <div class="site-section border-bottom" data-aos="fade">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-6">
                    <div class="block-16">
                        <figure>
                            <img src="~/images/blog_1.jpg" alt="Image placeholder" class="img-fluid rounded">
                            <a href="" class="play-button popup-vimeo"><span class="ion-md-play"></span></a>

                        </figure>
                    </div>
                </div>
                <div class="col-md-1"></div>
                <div class="col-md-5">


                    <div class="site-section-heading pt-3 mb-4">
                        <h2 class="text-black">How We Started</h2>
                    </div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius repellat, dicta at laboriosam, nemo exercitationem itaque eveniet architecto cumque, deleniti commodi molestias repellendus quos sequi hic fugiat asperiores illum. Atque, in, fuga excepturi corrupti error corporis aliquam unde nostrum quas.</p>
                    <p>Accusantium dolor ratione maiores est deleniti nihil? Dignissimos est, sunt nulla illum autem in, quibusdam cumque recusandae, laudantium minima repellendus.</p>

                </div>
            </div>
        </div>
    </div>

    <div class="site-section border-bottom" data-aos="fade">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <div class="col-md-7 site-section-heading text-center pt-4">
                    <h2>The Team</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-lg-3">

                    <div class="block-38 text-center">
                        <div class="block-38-img">
                            <div class="block-38-header">
                                <img src="~/images/person_1.jpg" alt="Image placeholder" class="mb-4">
                                <h3 class="block-38-heading h4">Elizabeth Graham</h3>
                                <p class="block-38-subheading">CEO/Co-Founder</p>
                            </div>
                            <div class="block-38-body">
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta. </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="block-38 text-center">
                        <div class="block-38-img">
                            <div class="block-38-header">
                                <img src="~/images/person_2.jpg" alt="Image placeholder" class="mb-4">
                                <h3 class="block-38-heading h4">Jennifer Greive</h3>
                                <p class="block-38-subheading">Co-Founder</p>
                            </div>
                            <div class="block-38-body">
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta. </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="block-38 text-center">
                        <div class="block-38-img">
                            <div class="block-38-header">
                                <img src="~/images/person_3.jpg" alt="Image placeholder" class="mb-4">
                                <h3 class="block-38-heading h4">Patrick Marx</h3>
                                <p class="block-38-subheading">Marketing</p>
                            </div>
                            <div class="block-38-body">
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta. </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="block-38 text-center">
                        <div class="block-38-img">
                            <div class="block-38-header">
                                <img src="~/images/person_4.jpg" alt="Image placeholder" class="mb-4">
                                <h3 class="block-38-heading h4">Mike Coolbert</h3>
                                <p class="block-38-subheading">Sales Manager</p>
                            </div>
                            <div class="block-38-body">
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae aut minima nihil sit distinctio recusandae doloribus ut fugit officia voluptate soluta. </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="site-section site-section-sm site-blocks-1 border-0" data-aos="fade">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
                    <div class="icon mr-4 align-self-start">
                        <span class="icon-truck"></span>
                    </div>
                    <div class="text">
                        <h2 class="text-uppercase">Free Shipping</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
                    <div class="icon mr-4 align-self-start">
                        <span class="icon-refresh2"></span>
                    </div>
                    <div class="text">
                        <h2 class="text-uppercase">Free Returns</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
                    <div class="icon mr-4 align-self-start">
                        <span class="icon-help"></span>
                    </div>
                    <div class="text">
                        <h2 class="text-uppercase">Customer Support</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan tincidunt fringilla.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>



</div>

ShoppingCart/Views/Home/Profile.cshtml
@model IEnumerable<ShoppingCart.Models.LoginRegister>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <link rel="stylesheet" href="~/css/profile.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" />
</head>





@*<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Profile</title>
</head>
<body>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PasswordConfirmed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PasswordConfirmed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LoginRegisterId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LoginRegisterId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LoginRegisterId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>
</html>*@
<body>
    @foreach(var item in Model){
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
	<div class="card p-4">
		<div class=" image d-flex flex-column justify-content-center align-items-center"> 
				 <img src="https://i.imgur.com/wvxPV9S.png" height="100"
                             width="100" />
                     <span class="name mt-3">@item.UserName</span> <span class="idd">@item.Email</span>
			<div class="d-flex flex-row justify-content-center align-items-center gap-2"> <span
					class="idd1">@item.Phone</span> <span><i class="fa fa-copy"></i></span> </div>
			<div class="d-flex flex-row justify-content-center align-items-center mt-3"> <span
						class="follow">Delivery Address : @item.Address</span> </div>
			<div class=" d-flex mt-2"> <a asp-controller="Login" asp-action="Edit" asp-route-id="@item.LoginRegisterId" class="btn1 btn-dark">Edit Profile</a> </div>
			<div class="text mt-3"> <span>Eleanor Pena is a creator of minimalistic x bold graphics and digital
					artwork.<br><br> Artist/ Creative Director by Day #NFT minting with FND night. </span> </div>
			
			<div class=" px-2 rounded mt-4 date "> <span class="join">Phone no : @item.Phone</span> </div>
		</div>
	</div>
</div>
    }
    
</body>
</html>

ShoppingCart/Views/Home/Shop.cshtml
@{Layout = "~/Views/Shared/_Layout.cshtml";}
@using ShoppingCart.Controllers;
@{
    int? i = Context.Session.GetInt32("countbrands");
} 
@model IEnumerable<Products>

    

<div class="site-wrap">

    
    <div class="bg-light py-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0"><a asp-controller="Home" asp-action="Shop">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Shop</strong></div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">

            <div class="row mb-5">
                <div class="col-md-9 order-2">

                    <div class="row">
                        <div class="col-md-12 mb-5">
                            <div class="float-md-left mb-4"><h2 class="text-black h5">Shop All</h2></div>
                            <div class="d-flex">
                                <div class="dropdown mr-1 ml-md-auto">
                                    <button type="button" class="btn btn-secondary btn-sm dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Latest
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                                        <a class="dropdown-item" href="#">Brands @i</a>
                                        <a class="dropdown-item" href="#">Women</a>
                                        <a class="dropdown-item" href="#">Children</a>
                                    </div>
                                </div>
                                @await Component.InvokeAsync("Categories")
                            </div>
                        </div>
                    </div>
                    <div class="row mb-5">

                        @foreach(var item in Model){

                        <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                            <div class="block-4 text-center border">
                                <figure class="block-4-image">
                                    <a asp-controller="Home" asp-action="ShopSingle" asp-route-id="@item.ProductId"><img src="@item.Pimage" alt="Image placeholder" class="img-fluid"></a>
                                </figure>
                                <div class="block-4-text p-4">
                                        <h3><a asp-controller="Home" asp-action="ShopSingle" asp-route-id="@item.ProductId">@item.Pname</a></h3>
                                    <p class="mb-0">@item.Subject</p>
                                    <p class="text-primary font-weight-bold">$@item.Price</p>
                                </div>
                            </div>
                        </div>
                        }
                       
                      

                       


                    </div>
                    <div class="row" data-aos="fade-up">
                        <div class="col-md-12 text-center">
                            <div class="site-block-27">
                                <ul>
                                    <li><a href="#">&lt;</a></li>
                                    <li class="active"><span>1</span></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li><a href="#">&gt;</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 order-1 mb-5 mb-md-0">
                    <div class="border p-4 rounded mb-4">
                        <h3 class="mb-3 h6 text-uppercase text-black d-block">Categories</h3>
                        <ul class="list-unstyled mb-0">
                            <li class="mb-1"><a href="#" class="d-flex"><span>Men</span> <span class="text-black ml-auto">(2,220)</span></a></li>
                            <li class="mb-1"><a href="#" class="d-flex"><span>Women</span> <span class="text-black ml-auto">(2,550)</span></a></li>
                            <li class="mb-1"><a href="#" class="d-flex"><span>Children</span> <span class="text-black ml-auto">(2,124)</span></a></li>
                        </ul>
                    </div>

                    <div class="border p-4 rounded mb-4">
                        <div class="mb-4">
                            <h3 class="mb-3 h6 text-uppercase text-black d-block">Filter by Price</h3>
                            <div id="slider-range" class="border-primary"></div>
                            <input type="text" name="text" id="amount" class="form-control border-0 pl-0 bg-white" disabled="" />
                        </div>

                        <div class="mb-4">
                            <h3 class="mb-3 h6 text-uppercase text-black d-block">Size</h3>
                            <label for="s_sm" class="d-flex">
                                <input type="checkbox" id="s_sm" class="mr-2 mt-1"> <span class="text-black">Small (2,319)</span>
                            </label>
                            <label for="s_md" class="d-flex">
                                <input type="checkbox" id="s_md" class="mr-2 mt-1"> <span class="text-black">Medium (1,282)</span>
                            </label>
                            <label for="s_lg" class="d-flex">
                                <input type="checkbox" id="s_lg" class="mr-2 mt-1"> <span class="text-black">Large (1,392)</span>
                            </label>
                        </div>

                        <div class="mb-4">
                            <h3 class="mb-3 h6 text-uppercase text-black d-block">Color</h3>
                            <a href="#" class="d-flex color-item align-items-center">
                                <span class="bg-danger color d-inline-block rounded-circle mr-2"></span> <span class="text-black">Red (2,429)</span>
                            </a>
                            <a href="#" class="d-flex color-item align-items-center">
                                <span class="bg-success color d-inline-block rounded-circle mr-2"></span> <span class="text-black">Green (2,298)</span>
                            </a>
                            <a href="#" class="d-flex color-item align-items-center">
                                <span class="bg-info color d-inline-block rounded-circle mr-2"></span> <span class="text-black">Blue (1,075)</span>
                            </a>
                            <a href="#" class="d-flex color-item align-items-center">
                                <span class="bg-primary color d-inline-block rounded-circle mr-2"></span> <span class="text-black">Purple (1,075)</span>
                            </a>
                        </div>

                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="site-section site-blocks-2">
                        <div class="row justify-content-center text-center mb-5">
                            <div class="col-md-7 site-section-heading pt-4">
                                <h2>Categories</h2>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
                                <a class="block-2-item" href="#">
                                    <figure class="image">
                                        <img src="~/images/women.jpg" alt="" class="img-fluid">
                                    </figure>
                                    <div class="text">
                                        <span class="text-uppercase">Collections</span>
                                        <h3>Women</h3>
                                    </div>
                                </a>
                            </div>
                            <div class="col-sm-6 col-md-6 col-lg-4 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="100">
                                <a class="block-2-item" href="#">
                                    <figure class="image">
                                        <img src="~/images/children.jpg" alt="" class="img-fluid">
                                    </figure>
                                    <div class="text">
                                        <span class="text-uppercase">Collections</span>
                                        <h3>Children</h3>
                                    </div>
                                </a>
                            </div>
                            <div class="col-sm-6 col-md-6 col-lg-4 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="200">
                                <a class="block-2-item" href="#">
                                    <figure class="image">
                                        <img src="~/images/men.jpg" alt="" class="img-fluid">
                                    </figure>
                                    <div class="text">
                                        <span class="text-uppercase">Collections</span>
                                        <h3>Men</h3>
                                    </div>
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>

</div>